food/urls.py
from django.conf.urls import url
from .views import index, add_meal, delete_meal, update_meal, view_meal

urlpatterns = [
	url(r'^$', index, name = 'index'),
	url(r'^add_meal$', add_meal, name = 'add-meal'),
	url(r'^delete_meal/(?P<meal_id>\d+)$', delete_meal, name = 'delete-meal'),
	url(r'^update_meal/(?P<meal_id>\d+)$', update_meal, name = 'update-meal'),
	url(r'^view_meal/(?P<meal_id>\d+)$', view_meal, name = 'view-meal'),
]

food_tracker/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(('food.urls','food'), namespace = "food")),
]

food/models.py
from django.db import models

# Create your models here.

class Food(models.Model):
	name = models.CharField(verbose_name="Food Name", max_length=200)
	calories = models.FloatField(verbose_name="Calories (kcal)")
	total_fat = models.FloatField(verbose_name="Total Fat (g)")
	saturated_fat = models.FloatField(verbose_name="Saturated Fat (g)")
	cholesterol = models.FloatField(verbose_name="Cholesterol (mg)")
	sodium = models.FloatField(verbose_name="Sodium (mg)")
	total_carbohydrate = models.FloatField(verbose_name="Total Carbohydrate (g)")
	dietary_fibre = models.FloatField(verbose_name="Dietary Fibre (g)")
	sugar = models.FloatField(verbose_name="Sugar (g)")
	protein = models.FloatField(verbose_name="Protein (g)")
	
	def __str__(self):
		return "%s" % self.name

class Meal(models.Model):
	BREAKFAST = 1
	MORNING_SNACK = 2
	LUNCH = 3
	AFTERNOON_SNACK = 4
	DINNER = 5
	EVENING_SNACK = 6
	MEAL_TIME_TYPES = (
		(BREAKFAST, "Breakfast"),
		(MORNING_SNACK, "Morning Snack"),
		(LUNCH, "Lunch"),
		(AFTERNOON_SNACK, "Afternoon Snack"),
		(DINNER, "Dinner"),
		(EVENING_SNACK, "Evening Snack")
	)
	food = models.ForeignKey(Food, verbose_name="Food", on_delete = models.CASCADE)
	serving_size = models.IntegerField(verbose_name="Serving Size")
	meal_time = models.IntegerField(verbose_name="Meal Time", choices = MEAL_TIME_TYPES)

	def __str__(self):
		return "%s" % self.food

	def get_total_calories(self):
		return self.serving_size * self.food.calories

food/forms.py
from django import forms
from .models import Meal

class MealForm(forms.ModelForm):
	class Meta:
		model = Meal
		fields = "__all__"

food/views.py
from django.shortcuts import render


# Create your views here.
from .models import Food, Meal
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from .forms import MealForm

def index(request):
	template = 'list.html'
	meals = Meal.objects.all()
	context = {
		'meals': meals,
	}
	return render(request, template, context)

def add_meal(request):
	template = "add_meal.html"
	if request.method == "POST":
		form = MealForm(request.POST)
		if form.is_valid():
			form.save()
		return HttpResponseRedirect(reverse_lazy('food:index'))
	else:
		context = {
			'meal_form': MealForm(),
		}
	return render(request, template, context)

def delete_meal(request, meal_id):
	meal = Meal.objects.get(id=int(meal_id))
	meal.delete()
	return HttpResponseRedirect(reverse_lazy('food:index'))

def update_meal(request, meal_id):
	template = "update_meal.html"
	meal = Meal.objects.get(id=int(meal_id))
	if request.method == "POST":
		form = MealForm(request.POST, instance = meal)
		if form.is_valid():
			form.save()
		return HttpResponseRedirect(reverse_lazy('food:index'))
	else:
		context = {
			'meal_form': MealForm(instance = meal),
		}
	return render(request, template, context)

#view
def view_meal(request, meal_id):
	template = 'view_meal.html'
	food = Food.objects.get(id=int(meal_id))
	meal = Meal.objects.get(id=int(meal_id))
	context = {
		'food' : food,
		'meal': meal,
	}
	return render(request, template, context)

templates/add_meal.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
	</head>
	<body>
		<h1>My Food Tracker - Add Meal</h1>

		<form role="form" action="" method="POST">
			{% csrf_token %}

			<table class="table table-striped table-bordered">
				<tr>
					<td>Food</td>
					<td>{{ meal_form.food }}</td>
				</tr>
				<tr>
					<td>Serving Size</td>
					<td>{{ meal_form.serving_size }}</td>
				</tr>
				<tr>
					<td>Meal Time</td>
					<td>{{ meal_form.meal_time }}</td>
				</tr>
			</table>

			<button class="btn btn-success" type="submit">Save</button>

		</form>

	</body>
</html>

templates/list.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
	</head>
	<body>
		<h1>My Food Tracker</h1>

		<a href="{% url 'food:add-meal' %}" class="btn btn-success">Add Meal</a> <br /><br />

		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th>Food</th>
					<th>Meal Time</th>
					<th>Total Calories</th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				{% for meal in meals %}
				<tr>
					<td>{{ meal.food.name }}</td>
					<td>{{ meal.get_meal_time_display }}</td>
					<td>{{ meal.get_total_calories }} kcal</td>
					<td>
						<a href="{% url 'food:view-meal' meal.food.id %}" class="btn btn-info">View</a>
					</td>
					<td>
						<a href="{% url 'food:update-meal' meal.id %}" class="btn btn-primary">Update</a>
					</td>
					<td>
						<a href="{% url 'food:delete-meal' meal.id %}" class="btn btn-danger">Delete</a>
					</td>
				</tr>
				{% empty %}
				<tr>
					<td colspan=6>No meals yet</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</body>
</html>

templates/update_meal.html

<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
	</head>
	<body>
		<h1>My Food Tracker - Update Meal</h1>

		<form role="form" action="" method="POST">
			{% csrf_token %}

			<table class="table table-striped table-bordered">
				<tr>
					<td>Food</td>
					<td>{{ meal_form.food }}</td>
				</tr>
				<tr>
					<td>Serving Size</td>
					<td>{{ meal_form.serving_size }}</td>
				</tr>
				<tr>
					<td>Meal Time</td>
					<td>{{ meal_form.meal_time }}</td>
				</tr>
			</table>

			<button class="btn btn-success" type="submit">Save</button>

		</form>

	</body>
</html>

templates/view_meal.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

</head>
	<body>
		<h1>My Food Tracker - View Meal</h1>

		<table class="table table-striped table-bordered">
		<tr>
			<td>Food</td>
			<td>{{ food.name }}</td>
		</tr>
		<tr>
			<td>Calories</td>
			<td>{{ food.calories }}</td>
		</tr>
		<tr>
			<td>Serving Size</td>
			<td>{{ meal.serving_size }}</td>
		</tr>
		<tr>
			<td>Total Fat</td>
			<td>{{ food.total_fat }}</td>
		</tr>
		<tr>
			<td>Saturated Fat</td>
			<td>{{ food.saturated_fat }}</td>
		</tr>
		<tr>
			<td>Cholesterol</td>
			<td>{{ food.cholesterol }}</td>
		</tr>
		<tr>
			<td>Sodium</td>
			<td>{{ food.sodium }}</td>
		</tr>
		<tr>
			<td>Total Carbohydrate</td>
			<td>{{ food.total_carbohydrate }}</td>
		</tr>
		<tr>
			<td>Dietary Fibre</td>
			<td>{{ food.dietary_fibre }}</td>
		</tr>
		<tr>
			<td>Sugar</td>
			<td>{{ food.sugar }}</td>
		</tr>
		<tr>
			<td>Protein</td>
			<td>{{ food.protein }}</td>
		</tr>
	</table>
	</body>
</html>

-->